name: Static analysis

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.3.1
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_ENV: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_TYPESCRIPT: true
          VALIDATE_YAML: true
          VALIDATE_YAML_PRETTIER: true
          DISABLE_ERRORS: false
          GITHUB_TOKEN: ${{ github.token }}
